### ISSUE TITLE
Why does the body have padding?

### ISSUE THREAD

**Issue by elie222** [markoshust/meteor-material-ui#10]
The body in my app has padding of 8px. Is this part of material design or is something not working for me?

**Comment by markshust** [comment]
this is part of browser chrome, has nothing to do with this library. just set it with css `body{padding:0}`

**Comment by elie222** [comment]
Ok. I assumed the library would've set that for me and css was missing
since that wasn't happening. Thanks

**Comment by duzy** [comment]
In your theme (e.g. `const theme = createMuiTheme({...})`)
```css
    '@global': {
        body: {
            margin: 0,
        },
    },
```
